### ISSUE TITLE
Dividir galeria de fotos en categorias

### ISSUE THREAD

**Issue by RicardoEscobar** [RicardoEscobar/montessori-ver#5]
# Dividir galería de fotos en categorías

Se requiere dividir `html/galeria.html` en las siguientes categorías:

- Instalaciones.
- Comunidad infantil (1 - 3 años)
- Casa de niños (3 - 6 años)
- Música.
- Yoga.
- Activación física.
- Ambiente externo.
- Escuela para padres.

## Notas
- No se agregará fotos nuevas a la galería.
- Se esta a la espera de recibir fotos definitivas.
- Repartir indiscriminadamente las fotos entre las categorías.

**Comment by RicardoEscobar** [comment]
Estaré trabajando en esta cuestion _issue_ junto con @cecilcm83

**Comment by cecilcm83** [comment]
ya esta terminado....

**Comment by RicardoEscobar** [comment]
Cerrado y terminado.
