### ISSUE TITLE
Agregar nivel escolar a formularios

### ISSUE THREAD

**Issue by RicardoEscobar** [RicardoEscobar/montessori-ver#8]
# Agregar nivel escolar a formularios
Agregar un `<input>` de algún tipo:
- Checkbox.
- Dropdown.
- Listbox.

Este se encarga de dar a elegir las siguientes opciones:

- Casa de los niños (1 - 3 años)
- Comunidad infantil (3 - 6 años)

Este cambio se realiza en el formulario `html/inscripciones.html` y a tu juicio decide si vale la pena ponerlo en `html/contacto.html`

**Comment by cecilcm83** [comment]
ok. trabajare en ese issu
